<?
$vars = array
(
//    "datasrcname" => "area_type", 
//    "savethis" => "no",
//    "param1" => "type",
//    "param2" => "type",
//    "block_values_h" => array
//        (
//            "0" => "page",
//        ),

 //   "color_values_h" => array
 //       (
 //           "0" => "page",
 //       ),

//    "panelx" => 500,
    "panely" => 400,
    "quantum" => "quantum",
//    "block_selected" => array
//        (
//            "0" => "page",
//        ),

//    "color_selected" => array
//        (
//            "0" => "page",
//        ),
//    "has_js" => 1,
);

$vars_block = array
(
    "datasrcname" => "donestech_drupal", 
    "savethis" => "no",
    "param1" => "type",
    "param2" => "type",
    "block_values_h" => array
        (
            "0" => "page",
        ),

    "color_values_h" => array
        (
            "0" => "page",
        ),

    "panelx" => 150,
    "panely" => 150,
    "quantum" => "quantum",
    "block_selected" => array
        (
            "0" => "page",
        ),

    "color_selected" => array
        (
            "0" => "page",
        ),
    "has_js" => 1,
)


?>
